.TH "sources/core/maths Directory Reference" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/core/maths Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbases\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbases_string\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmatrix\&.cpp\fP"
.br
.in -1c
