.TH "sources/core Directory Reference" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/core Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbricks\fP"
.br
.ti -1c
.RI "directory \fBConstructor\fP"
.br
.ti -1c
.RI "directory \fBmaths\fP"
.br
.ti -1c
.RI "directory \fButilitaires\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBrick\&.cpp\fP"
.br
.ti -1c
.RI "file \fBChoice\&.cpp\fP"
.br
.in -1c
