.TH "sources/core/maths/bases_string.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/core/maths/bases_string.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'term_prototypes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_put_nbr_base\fP (int nbr, std::string &base)"
.br
.ti -1c
.RI "void \fBbase_to_stream\fP (int nbr, std::string &base, std::stringstream &out)"
.br
.ti -1c
.RI "int \fBcheck_neg\fP (std::string &s, int mark)"
.br
.ti -1c
.RI "int \fBcheck_base\fP (std::string &base, int n)"
.br
.ti -1c
.RI "int \fBmy_getnbr_base\fP (std::string &str, std::string &base, int mark)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void base_to_stream (int nbr, std::string & base, std::stringstream & out)"

.SS "int check_base (std::string & base, int n)"

.SS "int check_neg (std::string & s, int mark)"

.SS "int my_getnbr_base (std::string & str, std::string & base, int mark)"

.SS "int my_put_nbr_base (int nbr, std::string & base)"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
