.TH "sources/core/maths/bases.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/core/maths/bases.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'my_maths\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_put_nbr_base\fP (int nbr, const char *base)"
.br
.ti -1c
.RI "int \fBcheck_neg\fP (const char *s)"
.br
.ti -1c
.RI "int \fBcheck_base\fP (const char *base, int n)"
.br
.ti -1c
.RI "int \fBmy_getnbr_base\fP (const char *str, const char *base)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int check_base (const char * base, int n)"

.SS "int check_neg (const char * s)"

.SS "int my_getnbr_base (const char * str, const char * base)"

.SS "int my_put_nbr_base (int nbr, const char * base)"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
