.TH "includes/core/Brick.hpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/core/Brick.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBrick\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
