.TH "Cesars" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cesars \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Cesars\&.hpp>\fP
.PP
Inherits \fBBrick\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCesars\fP ()"
.br
.ti -1c
.RI "\fB~Cesars\fP ()"
.br
.ti -1c
.RI "void \fBpresent\fP ()"
.br
.ti -1c
.RI "void \fBget_key\fP ()"
.br
.ti -1c
.RI "\fBBrick::identity\fP \fBwho\fP ()"
.br
.ti -1c
.RI "void \fBget_lib\fP (int lib)"
.br
.ti -1c
.RI "\fBCheck_Cesars\fP \fBkey_check\fP (int key)"
.br
.ti -1c
.RI "std::string \fBchiffre\fP (std::string &input)"
.br
.ti -1c
.RI "std::string \fBdechiffre\fP (std::string &input)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fB_key\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Cesars::Cesars ()"

.SS "Cesars::~Cesars ()"

.SH "Member Function Documentation"
.PP 
.SS "std::string Cesars::chiffre (std::string & input)\fC [virtual]\fP"

.PP
Implements \fBBrick\fP\&.
.SS "std::string Cesars::dechiffre (std::string & input)\fC [virtual]\fP"

.PP
Implements \fBBrick\fP\&.
.SS "void Cesars::get_key ()\fC [virtual]\fP"

.PP
Implements \fBBrick\fP\&.
.SS "void Cesars::get_lib (int lib)"

.SS "\fBCheck_Cesars\fP Cesars::key_check (int key)"

.SS "void Cesars::present ()\fC [virtual]\fP"

.PP
Implements \fBBrick\fP\&.
.SS "\fBBrick::identity\fP Cesars::who ()\fC [virtual]\fP"

.PP
Implements \fBBrick\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Cesars::_key\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
