.TH "sources/term/chiffrement/cesars.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/term/chiffrement/cesars.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'term_prototypes\&.h'\fP
.br
\fC#include 'utilitaires\&.h'\fP
.br
\fC#include 'Choice\&.hpp'\fP
.br
\fC#include 'Cesars\&.hpp'\fP
.br
\fC#include 'Brick\&.hpp'\fP
.br
\fC#include 'Constructor\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcesars_user_choices\fP ()"
.br
.ti -1c
.RI "int \fBcesars_choices\fP (int choice)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int cesars_choices (int choice)"

.SS "int cesars_user_choices ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
