.TH "includes/core/Cesars.hpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/core/Cesars.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br
\fC#include 'Brick\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCesars\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCheck_Cesars\fP { \fBBAD_VALUE\fP = 1, \fBBAD_MODULO\fP = 2, \fBGOOD\fP = 3 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCheck_Cesars\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBAD_VALUE \fP\fP
.TP
\fB\fIBAD_MODULO \fP\fP
.TP
\fB\fIGOOD \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
