.TH "Choice" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Choice \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Choice\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBmenu_choice\fP (int min, int max)"
.br
.ti -1c
.RI "\fBChoice\fP ()"
.br
.ti -1c
.RI "\fB~Choice\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Choice::Choice ()"

.SS "Choice::~Choice ()"

.SH "Member Function Documentation"
.PP 
.SS "int Choice::menu_choice (int min, int max)"


.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
