.TH "sources/core/utilitaires/color_str.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/core/utilitaires/color_str.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'utilitaires\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template void \fBc_str< std::string & >\fP (std::string &str, char color, int thick)"
.br
.ti -1c
.RI "template void \fBc_str< char * >\fP (char *str, char color, int thick)"
.br
.ti -1c
.RI "template void \fBc_str< const char * >\fP (const char *str, char color, int thick)"
.br
.ti -1c
.RI "template<typename T > void \fBc_str\fP (T str, char color, int thick)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > void c_str (T str, char color, int thick)"

.SS "template void \fBc_str\fP< char * > (char * str, char color, int thick)"

.SS "template void \fBc_str\fP< const char * > (const char * str, char color, int thick)"

.SS "template void \fBc_str\fP< std::string & > (std::string & str, char color, int thick)"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
