.TH "sources/core/Constructor/Constructor_status.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/core/Constructor/Constructor_status.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'Constructor\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
