.TH "sources/term/info.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/term/info.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'term_prototypes\&.h'\fP
.br
\fC#include 'utilitaires\&.h'\fP
.br
\fC#include 'Choice\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinfo_C_and_V\fP ()"
.br
.ti -1c
.RI "void \fBinfo_102\fP ()"
.br
.ti -1c
.RI "void \fBinfo_v102\fP ()"
.br
.ti -1c
.RI "void \fBinfo_alpha\fP ()"
.br
.ti -1c
.RI "void \fBdisplay_info\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void display_info ()"

.SS "void info_102 ()"

.SS "void info_alpha ()"

.SS "void info_C_and_V ()"

.SS "void info_v102 ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
