.TH "includes/instant/instant_prototypes.h" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/instant/instant_prototypes.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain_instant\fP (int ac, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main_instant (int ac, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
