.TH "sources/core/utilitaires/isin.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/core/utilitaires/isin.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'utilitaires\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template int \fBmy_isin< char * >\fP (char c, char *str)"
.br
.ti -1c
.RI "template int \fBmy_isin< const char * >\fP (char c, const char *str)"
.br
.ti -1c
.RI "template int \fBmy_isin< std::string & >\fP (char c, std::string &str)"
.br
.ti -1c
.RI "template int \fBmy_isin< const std::string & >\fP (char c, const std::string &str)"
.br
.ti -1c
.RI "template<typename T > int \fBmy_isin\fP (char c, T str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > int my_isin (char c, T str)"

.SS "template int \fBmy_isin\fP< char * > (char c, char * str)"

.SS "template int \fBmy_isin\fP< const char * > (char c, const char * str)"

.SS "template int \fBmy_isin\fP< const std::string & > (char c, const std::string & str)"

.SS "template int \fBmy_isin\fP< std::string & > (char c, std::string & str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
