.TH "sources/core/utilitaires/lib_check.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/core/utilitaires/lib_check.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'utilitaires\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBlib_char_check\fP (int libi, std::string const &input)"
.br
.ti -1c
.RI "bool \fBlib_bool_check\fP (int libi, std::string const &input)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool lib_bool_check (int libi, std::string const & input)"

.SS "char lib_char_check (int libi, std::string const & input)"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
