.TH "sources/instant/main_instant.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/instant/main_instant.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'instant_prototypes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain_instant\fP (int ac, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main_instant (int ac, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
