.TH "sources/term/main_term.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/term/main_term.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'term_prototypes\&.h'\fP
.br
\fC#include 'Choice\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain_term\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main_term ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
