.TH "sources/main.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <functional>\fP
.br
\fC#include 'term_prototypes\&.h'\fP
.br
\fC#include 'sdl/sdl_prototypes\&.h'\fP
.br
\fC#include 'qt5/qt5_prototypes\&.h'\fP
.br
\fC#include 'instant_prototypes\&.h'\fP
.br
\fC#include 'utilitaires\&.h'\fP
.br
\fC#include 'Choice\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int ac, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Matthieu Raynaud de Fitte 
.RE
.PP
\fBVersion:\fP
.RS 4
3\&.6 
.RE
.PP
\fBDate:\fP
.RS 4
10 janvier 2014
.RE
.PP
Programme de chiffrement 
.SH "Function Documentation"
.PP 
.SS "int main (int ac, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
