.TH "sources/graph/qt5/main_qt5.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/graph/qt5/main_qt5.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'qt5/qt5_prototypes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain_qt5\fP (int ac, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main_qt5 (int ac, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
