.TH "sources/core/maths/matrix.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/core/maths/matrix.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'term_prototypes\&.h'\fP
.br
\fC#include 'utilitaires\&.h'\fP
.br
\fC#include 'my_maths\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBresize_matrix\fP (MatrixXd &out, int words)"
.br
.ti -1c
.RI "void \fBmatrix_initialisator\fP (MatrixXd &matrix)"
.br
.ti -1c
.RI "void \fBuser_input_to_matrix\fP (MatrixXd &out, std::string &input, const char *lib)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void matrix_initialisator (MatrixXd & matrix)"

.SS "void resize_matrix (MatrixXd & out, int words)"

.SS "void user_input_to_matrix (MatrixXd & out, std::string & input, const char * lib)"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
