.TH "includes/term/term_prototypes.h" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/term/term_prototypes.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <Eigen/Dense>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain_term\fP ()"
.br
.ti -1c
.RI "int \fBE_102_user_choices\fP ()"
.br
.ti -1c
.RI "int \fBE_102_choices\fP (int choice)"
.br
.ti -1c
.RI "int \fBV_102_user_choices\fP ()"
.br
.ti -1c
.RI "void \fBV_102_choices\fP (int choice)"
.br
.ti -1c
.RI "int \fBcesars_choices\fP (int choice)"
.br
.ti -1c
.RI "int \fBcesars_user_choices\fP ()"
.br
.ti -1c
.RI "void \fBinfo_C_and_V\fP ()"
.br
.ti -1c
.RI "void \fBinfo_102\fP ()"
.br
.ti -1c
.RI "void \fBinfo_v102\fP ()"
.br
.ti -1c
.RI "void \fBinfo_alpha\fP ()"
.br
.ti -1c
.RI "void \fBdisplay_info\fP ()"
.br
.ti -1c
.RI "int \fBvigenere_choices\fP (int choice)"
.br
.ti -1c
.RI "int \fBvigenere_user_choices\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int cesars_choices (int choice)"

.SS "int cesars_user_choices ()"

.SS "void display_info ()"

.SS "int E_102_choices (int choice)"

.SS "int E_102_user_choices ()"

.SS "void info_102 ()"

.SS "void info_alpha ()"

.SS "void info_C_and_V ()"

.SS "void info_v102 ()"

.SS "int main_term ()"

.SS "void V_102_choices (int choice)"

.SS "int V_102_user_choices ()"

.SS "int vigenere_choices (int choice)"

.SS "int vigenere_user_choices ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
