.TH "sources/core/utilitaires/user_input.cpp" 3 "Sun Sep 27 2015" "encode-o-matic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/core/utilitaires/user_input.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'term_prototypes\&.h'\fP
.br
\fC#include 'utilitaires\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBuser_input\fP ()"
.br
.ti -1c
.RI "void \fBuser_string\fP (std::string &in)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int user_input ()"

.SS "void user_string (std::string & in)"

.SH "Author"
.PP 
Generated automatically by Doxygen for encode-o-matic from the source code\&.
